# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven
on:
  push:
    branches: [ feature ]
 # pull_request:
    #branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and test with Maven
      #run: mvn -B package --file pom.xml
    #- name: 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      
    #- name: SonarCloud Scan
     # uses: SonarSource/sonarcloud-github-action@v1.5
    - name : Validate Target Folder and compiled files
      run: |
         cd target
         ls -a
    - name : Merge the feature branch in to main
      uses: tukasz/direct-merge-action@v2.0.2
      with:
        source-branch: feature
    # Name of the target branch (to)
        target-branch: main
    # Message to use for the commit. If empty then a default message will be used ("Automatic merge of <source-branch> -> <target-branch>")
 
    # Repository access token. For example: secrets.GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
          args: --docker
      env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "gansky/ciexercise-spring-petclinic"
          TAG_NAME: "$GITHUB_SHA"
          LATEST: "false" 







